//! First-run project initialization.

use std::fs;
use std::path::Path;

use crate::classification::Classification;
use crate::config::ProductConfig;
use crate::error::{ProductError, Result};
use crate::privacy::{NetworkMode, PrivacyMode};
use crate::store::validate_output_path;

#[derive(Debug, Clone, Default)]
pub struct InitOptions {
    pub force: bool,
    pub project_name: Option<String>,
    pub confidential: bool,
}

/// Create `.dare-security/config.yaml` and runs directory scaffold.
pub fn init_project(root: &Path, options: &InitOptions) -> Result<ProductConfig> {
    validate_output_path(root)?;
    let dare_dir = root.join(".dare-security");
    let config_path = dare_dir.join("config.yaml");
    if config_path.exists() && !options.force {
        return Err(ProductError::configuration(format!(
            "config already exists at {}; use --force to overwrite",
            config_path.display()
        )));
    }
    fs::create_dir_all(dare_dir.join("runs"))?;
    let mut cfg = ProductConfig::default();
    cfg.project.name = options
        .project_name
        .clone()
        .or_else(|| {
            root.file_name()
                .and_then(|n| n.to_str())
                .map(|s| s.to_owned())
        })
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unnamed-project".to_owned());
    if options.confidential {
        cfg.privacy.mode = PrivacyMode::Confidential;
        cfg.privacy.telemetry = false;
        cfg.privacy.network = NetworkMode::Denied;
        cfg.privacy.offline = true;
        cfg.classification = Classification::confidential_default();
    }
    cfg.validate()?;
    let yaml = cfg.to_yaml()?;
    fs::write(&config_path, yaml)?;
    let readme = dare_dir.join("README.md");
    if !readme.exists() || options.force {
        fs::write(
            readme,
            "# DARE Agent Security local store\n\n\
             Generated by `dare-agent-security init`.\n\n\
             - `config.yaml` — product config v1\n\
             - `runs/` — assessment artifacts (summary, findings, reports)\n\n\
             Safe defaults are static/passive/plan-only. Confidential/offline modes are fail-closed.\n",
        )?;
    }
    Ok(cfg)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn init_writes_config() {
        let dir = tempdir().unwrap();
        let cfg = init_project(dir.path(), &InitOptions::default()).unwrap();
        assert!(dir.path().join(".dare-security/config.yaml").is_file());
        assert_eq!(cfg.version, "1");
        assert!(!cfg.privacy.telemetry);
    }

    #[test]
    fn init_refuses_overwrite_without_force() {
        let dir = tempdir().unwrap();
        init_project(dir.path(), &InitOptions::default()).unwrap();
        assert!(init_project(dir.path(), &InitOptions::default()).is_err());
    }
}
