#!/usr/bin/env python3
"""Regenerate `DARE/.canvas.md` from a cycle's `TASKS.md`.

The canvas is the live view of a cycle's progress. It had drifted twice —
showing Cycle 017 while Cycle 018 ran, then Cycle 018's mid-flight count after
that cycle had merged — because it was written by hand each time. Deriving it
from the checkbox list means it cannot say something the task list does not.

Usage:
    python scripts/regen-canvas.py                 # newest cycle directory
    python scripts/regen-canvas.py 019             # a specific cycle
"""

import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
CYCLES = ROOT / "DARE" / "cycles"
CANVAS = ROOT / "DARE" / ".canvas.md"

ROW = re.compile(r"^- \[( |x)\] (task-\d{3}) — (.+?)(?:\s*\((AC-.*)\))?\s*$", re.M)


def pick_cycle(argument: str | None) -> pathlib.Path:
    directories = sorted(d for d in CYCLES.iterdir() if d.is_dir())
    if argument:
        matches = [d for d in directories if d.name.startswith(argument)]
        if not matches:
            raise SystemExit(f"no cycle directory starts with {argument!r}")
        return matches[0]
    return directories[-1]


def main() -> int:
    cycle = pick_cycle(sys.argv[1] if len(sys.argv) > 1 else None)
    tasks = (cycle / "TASKS.md").read_text(encoding="utf-8")
    rows = ROW.findall(tasks)
    if not rows:
        raise SystemExit(f"{cycle.name}/TASKS.md has no task checkboxes")

    done = sum(1 for mark, _, _, _ in rows if mark == "x")
    total = len(rows)
    percent = round(100 * done / total)
    number, _, slug = cycle.name.partition("-")

    title_line = tasks.splitlines()[0].lstrip("# ").strip()

    lines = [
        f"# DARE DAG Execution — Cycle {number} — Tasks",
        "",
        f"**Cycle:** {title_line}  ",
        f"**Cycle directory:** `DARE/cycles/{cycle.name}`  ",
        f"**Cycle status:** {'COMPLETE' if done == total else 'IN PROGRESS'}  ",
        "**Updated:** "
        + datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "",
        "Generated by `scripts/regen-canvas.py` from this cycle's `TASKS.md`.",
        "",
        "## Tasks",
        "",
        "| ID | Title | Status |",
        "|----|-------|--------|",
    ]
    for mark, task_id, title, _ in rows:
        lines.append(f"| {task_id} | {title.strip()} | {'DONE' if mark == 'x' else 'PENDING'} |")

    filled = percent // 5
    lines += [
        "",
        f"## Progress: {done}/{total} tasks ({percent}%)",
        "",
        "#" * filled + "." * (20 - filled) + f" {percent}%",
        "",
    ]

    CANVAS.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{cycle.name}: {done}/{total} ({percent}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
